// Date: 4/9/2014 5:57:41 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.sudwood.advancedutilities.client.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTube extends AdvancedModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape28;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
  
  public ModelTube()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape1.setRotationPoint(-0.5F, 23F, -0.5F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 8);
      Shape2.addBox(0F, 0F, 0F, 3, 2, 3);
      Shape2.setRotationPoint(-1.5F, 21F, -1.5F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 15, 0);
      Shape3.addBox(0F, 0F, 0F, 5, 12, 5);
      Shape3.setRotationPoint(-2.5F, 9F, -2.5F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 37, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 1, 5);
      Shape4.setRotationPoint(-2.5F, 8F, -2.5F);
      Shape4.setTextureSize(128, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 37, 9);
      Shape5.addBox(0F, 0F, 0F, 1, 1, 5);
      Shape5.setRotationPoint(7F, 13F, -2.5F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 51, 0);
      Shape6.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape6.setRotationPoint(-1.5F, 8F, 1.5F);
      Shape6.setTextureSize(128, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 51, 0);
      Shape7.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape7.setRotationPoint(-1.5F, 8F, -2.5F);
      Shape7.setTextureSize(128, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape28 = new ModelRenderer(this, 37, 0);
      Shape28.addBox(0F, 0F, 0F, 1, 1, 5);
      Shape28.setRotationPoint(1.5F, 8F, -2.5F);
      Shape28.setTextureSize(128, 128);
      Shape28.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 70, 0);
      Shape8.addBox(0F, 0F, 0F, 5, 5, 5);
      Shape8.setRotationPoint(-7F, 13F, -2.5F);
      Shape8.setTextureSize(128, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 37, 9);
      Shape9.addBox(0F, 0F, 0F, 1, 1, 5);
      Shape9.setRotationPoint(7F, 17F, -2.5F);
      Shape9.setTextureSize(128, 128);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 62, 0);
      Shape11.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape11.setRotationPoint(7F, 14F, -2.5F);
      Shape11.setTextureSize(128, 128);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 62, 0);
      Shape12.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape12.setRotationPoint(7F, 14F, 1.5F);
      Shape12.setTextureSize(128, 128);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 70, 0);
      Shape13.addBox(0F, 0F, 0F, 5, 5, 5);
      Shape13.setRotationPoint(2F, 13F, -2.5F);
      Shape13.setTextureSize(128, 128);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 62, 0);
      Shape14.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape14.setRotationPoint(-8F, 14F, -2.5F);
      Shape14.setTextureSize(128, 128);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 37, 9);
      Shape15.addBox(0F, 0F, 0F, 1, 1, 5);
      Shape15.setRotationPoint(-8F, 13F, -2.5F);
      Shape15.setTextureSize(128, 128);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 62, 0);
      Shape16.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape16.setRotationPoint(-8F, 14F, 1.5F);
      Shape16.setTextureSize(128, 128);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 37, 9);
      Shape17.addBox(0F, 0F, 0F, 1, 1, 5);
      Shape17.setRotationPoint(-8F, 17F, -2.5F);
      Shape17.setTextureSize(128, 128);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 18, 22);
      Shape18.addBox(0F, 0F, 0F, 5, 5, 5);
      Shape18.setRotationPoint(-2.5F, 13F, -7F);
      Shape18.setTextureSize(128, 128);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 0, 31);
      Shape19.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape19.setRotationPoint(-2.5F, 13F, -8F);
      Shape19.setTextureSize(128, 128);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 0, 31);
      Shape20.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape20.setRotationPoint(-2.5F, 13F, 7F);
      Shape20.setTextureSize(128, 128);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 0, 40);
      Shape21.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape21.setRotationPoint(-1.5F, 17F, 7F);
      Shape21.setTextureSize(128, 128);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 0, 40);
      Shape22.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape22.setRotationPoint(-1.5F, 17F, -8F);
      Shape22.setTextureSize(128, 128);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 18, 22);
      Shape23.addBox(0F, 0F, 0F, 5, 5, 5);
      Shape23.setRotationPoint(-2.5F, 13F, 2F);
      Shape23.setTextureSize(128, 128);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 0, 31);
      Shape24.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape24.setRotationPoint(1.5F, 13F, -8F);
      Shape24.setTextureSize(128, 128);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      Shape25 = new ModelRenderer(this, 0, 40);
      Shape25.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape25.setRotationPoint(-1.5F, 13F, -8F);
      Shape25.setTextureSize(128, 128);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, 0F);
      Shape26 = new ModelRenderer(this, 0, 31);
      Shape26.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape26.setRotationPoint(1.5F, 13F, 7F);
      Shape26.setTextureSize(128, 128);
      Shape26.mirror = true;
      setRotation(Shape26, 0F, 0F, 0F);
      Shape27 = new ModelRenderer(this, 0, 40);
      Shape27.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape27.setRotationPoint(-1.5F, 13F, 7F);
      Shape27.setTextureSize(128, 128);
      Shape27.mirror = true;
      setRotation(Shape27, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape28.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
  }
  
  public void render(float f5)
  {
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape28.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
  }
  
  public void renderBase(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape28.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
  }
  
  public void render1(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    Shape5.render(f5);
    Shape9.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
  }
  public void render2(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    Shape8.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
  }
  public void render3(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    Shape18.render(f5);
    Shape19.render(f5);
    Shape22.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
  }
  public void render4(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    Shape20.render(f5);
    Shape21.render(f5);
    Shape23.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
