// Date: 7/24/2015 2:14:02 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.sudwood.advancedutilities.client.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelQuarryFrame extends AdvancedModelBase
{
  //fields
    ModelRenderer middle;
    ModelRenderer y2;
    ModelRenderer y1;
    ModelRenderer x1;
    ModelRenderer x2;
    ModelRenderer z2;
    ModelRenderer z1;
  
  public ModelQuarryFrame()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      middle = new ModelRenderer(this, 0, 0);
      middle.addBox(0F, 0F, 0F, 3, 3, 3);
      middle.setRotationPoint(-1.5F, 15F, -1.5F);
      middle.setTextureSize(64, 32);
      middle.mirror = true;
      setRotation(middle, 0F, 0F, 0F);
      y2 = new ModelRenderer(this, 0, 0);
      y2.addBox(0F, 0F, 0F, 3, 6, 3);
      y2.setRotationPoint(-1.5F, 18F, -1.5F);
      y2.setTextureSize(64, 32);
      y2.mirror = true;
      setRotation(y2, 0F, 0F, 0F);
      y1 = new ModelRenderer(this, 0, 0);
      y1.addBox(0F, 0F, 0F, 3, 7, 3);
      y1.setRotationPoint(-1.5F, 8F, -1.5F);
      y1.setTextureSize(64, 32);
      y1.mirror = true;
      setRotation(y1, 0F, 0F, 0F);
      x1 = new ModelRenderer(this, 0, 0);
      x1.addBox(0F, 0F, 0F, 7, 3, 3);
      x1.setRotationPoint(-8.5F, 15F, -1.5F);
      x1.setTextureSize(64, 32);
      x1.mirror = true;
      setRotation(x1, 0F, 0F, 0F);
      x2 = new ModelRenderer(this, 0, 0);
      x2.addBox(0F, 0F, 0F, 6, 3, 3);
      x2.setRotationPoint(1.5F, 15F, -1.5F);
      x2.setTextureSize(64, 32);
      x2.mirror = true;
      setRotation(x2, 0F, 0F, 0F);
      z2 = new ModelRenderer(this, 0, 0);
      z2.addBox(0F, 0F, 0F, 3, 3, 7);
      z2.setRotationPoint(-1.5F, 15F, -8.5F);
      z2.setTextureSize(64, 32);
      z2.mirror = true;
      setRotation(z2, 0F, 0F, 0F);
      z1 = new ModelRenderer(this, 0, 0);
      z1.addBox(0F, 0F, 0F, 3, 3, 6);
      z1.setRotationPoint(-1.5F, 15F, 1.5F);
      z1.setTextureSize(64, 32);
      z1.mirror = true;
      setRotation(z1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    middle.render(f5);
    y2.render(f5);
    y1.render(f5);
    x1.render(f5);
    x2.render(f5);
    z2.render(f5);
    z1.render(f5);
  }
  
  public void render(float f5)
  {
    middle.render(f5);
    y2.render(f5);
    y1.render(f5);
    x1.render(f5);
    x2.render(f5);
    z2.render(f5);
    z1.render(f5);
  }
  
  public void renderbase(float f5)
  {
	  middle.render(f5);
  }
  public void render0(float f5) // -y
  {
	  y2.render(f5);
  }
  public void render1(float f5) // +y
  {
	  y1.render(f5);
  }
  public void render2(float f5) // north -z
  {
	  z2.render(f5);
  }
  public void render3(float f5) // south +z
  {
	  z1.render(f5);
  }
  public void render4(float f5) // west -x
  {
	  x2.render(f5);
  }
  public void render5(float f5) // east +x
  {
	  x1.render(f5);
  }
  
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
