// Date: 8/15/2014 3:12:11 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.sudwood.advancedutilities.client.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTomatoPlant extends AdvancedModelBase
{
  //fields
    ModelRenderer planted1;
    ModelRenderer planted2;
    ModelRenderer sprout1;
    ModelRenderer sprout2;
    ModelRenderer sprout3;
    ModelRenderer sprout4;
    ModelRenderer growing;
    ModelRenderer grown1;
    ModelRenderer grown2;
    ModelRenderer grown3;
    ModelRenderer grown4;
    ModelRenderer grown5;
    ModelRenderer grown6;
    ModelRenderer grown7;
    ModelRenderer grown8;
    ModelRenderer grown9;
    ModelRenderer harvest1;
    ModelRenderer harvest2;
    ModelRenderer harvest3;
    ModelRenderer harvest4;
    ModelRenderer harvest5;
    ModelRenderer harvest6;
    ModelRenderer harvest7;
    ModelRenderer harvest8;
    ModelRenderer harvest9;
    ModelRenderer harvest10;
    ModelRenderer harvest11;
    ModelRenderer harvest12;
    ModelRenderer harvest13;
    ModelRenderer harvest14;
  
  public ModelTomatoPlant()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      planted1 = new ModelRenderer(this, 14, 0);
      planted1.addBox(0F, 0F, 0F, 2, 1, 2);
      planted1.setRotationPoint(-1F, 24F, -1F);
      planted1.setTextureSize(128, 128);
      planted1.mirror = true;
      setRotation(planted1, 0F, 0F, 0F);
      planted2 = new ModelRenderer(this, 0, 0);
      planted2.addBox(0F, 0F, 0F, 3, 6, 3);
      planted2.setRotationPoint(-1.5F, 18F, -1.5F);
      planted2.setTextureSize(128, 128);
      planted2.mirror = true;
      setRotation(planted2, 0F, 0F, 0F);
      sprout1 = new ModelRenderer(this, 23, 0);
      sprout1.addBox(0F, 0F, 0F, 4, 1, 1);
      sprout1.setRotationPoint(1.2F, 21F, -0.5F);
      sprout1.setTextureSize(128, 128);
      sprout1.mirror = true;
      setRotation(sprout1, 0F, 0F, -0.4089647F);
      sprout2 = new ModelRenderer(this, 23, 0);
      sprout2.addBox(0F, 0F, 0F, 4, 1, 1);
      sprout2.setRotationPoint(-1.1F, 21F, 0.5F);
      sprout2.setTextureSize(128, 128);
      sprout2.mirror = true;
      setRotation(sprout2, 0F, -3.141593F, -0.4089647F);
      sprout3 = new ModelRenderer(this, 35, 0);
      sprout3.addBox(0F, 0F, 0F, 3, 0, 3);
      sprout3.setRotationPoint(-7F, 19.7F, -1F);
      sprout3.setTextureSize(128, 128);
      sprout3.mirror = true;
      setRotation(sprout3, -0.0371786F, 0.1858931F, -0.1858931F);
      sprout4 = new ModelRenderer(this, 35, 0);
      sprout4.addBox(0F, 0F, 0F, 3, 0, 3);
      sprout4.setRotationPoint(7F, 19.7F, 1.5F);
      sprout4.setTextureSize(128, 128);
      sprout4.mirror = true;
      setRotation(sprout4, -0.0371786F, 3.141593F, -0.1858931F);
      growing = new ModelRenderer(this, 50, 0);
      growing.addBox(0F, 0F, 0F, 3, 9, 3);
      growing.setRotationPoint(-1.5F, 9F, -1.5F);
      growing.setTextureSize(128, 128);
      growing.mirror = true;
      setRotation(growing, 0F, 0F, 0F);
      grown1 = new ModelRenderer(this, 68, 0);
      grown1.addBox(0F, 0F, 0F, 6, 1, 1);
      grown1.setRotationPoint(1.4F, 12F, -0.5F);
      grown1.setTextureSize(128, 128);
      grown1.mirror = true;
      setRotation(grown1, 0F, 0F, -0.3346075F);
      grown2 = new ModelRenderer(this, 68, 0);
      grown2.addBox(0F, 0F, 0F, 6, 1, 1);
      grown2.setRotationPoint(-0.5F, 15F, -1.3F);
      grown2.setTextureSize(128, 128);
      grown2.mirror = true;
      setRotation(grown2, 0F, 1.570796F, -0.3346075F);
      grown3 = new ModelRenderer(this, 68, 0);
      grown3.addBox(0F, 0F, 0F, 6, 1, 1);
      grown3.setRotationPoint(-1.3F, 12F, 0.5F);
      grown3.setTextureSize(128, 128);
      grown3.mirror = true;
      setRotation(grown3, 0F, -3.141593F, -0.3346075F);
      grown4 = new ModelRenderer(this, 68, 0);
      grown4.addBox(0F, 0F, 0F, 6, 1, 1);
      grown4.setRotationPoint(0.5F, 15F, 1.3F);
      grown4.setTextureSize(128, 128);
      grown4.mirror = true;
      setRotation(grown4, 0F, -1.570796F, -0.3346075F);
      grown5 = new ModelRenderer(this, 35, 20);
      grown5.addBox(0F, 0F, 0F, 2, 0, 3);
      grown5.setRotationPoint(-6F, 10.8F, 0F);
      grown5.setTextureSize(128, 128);
      grown5.mirror = true;
      setRotation(grown5, -0.0743572F, 0.1858931F, 0.3171542F);
      grown6 = new ModelRenderer(this, 35, 20);
      grown6.addBox(0F, 0F, 0F, 2, 0, 3);
      grown6.setRotationPoint(4F, 11.4F, 0F);
      grown6.setTextureSize(128, 128);
      grown6.mirror = true;
      setRotation(grown6, -0.1115358F, 3.141593F, 0.1684398F);
      grown7 = new ModelRenderer(this, 35, 20);
      grown7.addBox(0F, 0F, 0F, 2, 0, 3);
      grown7.setRotationPoint(-3F, 11.4F, 0F);
      grown7.setTextureSize(128, 128);
      grown7.mirror = true;
      setRotation(grown7, -0.0743572F, 3.141593F, -0.3520608F);
      grown8 = new ModelRenderer(this, 35, 12);
      grown8.addBox(0F, 0F, 0F, 2, 0, 5);
      grown8.setRotationPoint(-3F, 14.4F, -3F);
      grown8.setTextureSize(128, 128);
      grown8.mirror = true;
      setRotation(grown8, -0.0743572F, 1.542912F, -0.3520608F);
      grown9 = new ModelRenderer(this, 35, 6);
      grown9.addBox(0F, 0F, 0F, 2, 0, 4);
      grown9.setRotationPoint(-1.5F, 14.4F, 5F);
      grown9.setTextureSize(128, 128);
      grown9.mirror = true;
      setRotation(grown9, -0.0743572F, 2.026234F, 0.1684398F);
      harvest1 = new ModelRenderer(this, 0, 14);
      harvest1.addBox(0F, 0F, 0F, 2, 2, 2);
      harvest1.setRotationPoint(-8F, 12F, -1F);
      harvest1.setTextureSize(128, 128);
      harvest1.mirror = true;
      setRotation(harvest1, 0F, 0F, 0F);
      harvest2 = new ModelRenderer(this, 0, 11);
      harvest2.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest2.setRotationPoint(-7.5F, 14F, -0.5F);
      harvest2.setTextureSize(128, 128);
      harvest2.mirror = true;
      setRotation(harvest2, 0F, 0F, 0F);
      harvest3 = new ModelRenderer(this, 0, 11);
      harvest3.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest3.setRotationPoint(-7.5F, 11F, -0.5F);
      harvest3.setTextureSize(128, 128);
      harvest3.mirror = true;
      setRotation(harvest3, 0F, 0F, 0F);
      harvest4 = new ModelRenderer(this, 0, 11);
      harvest4.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest4.setRotationPoint(-7.5F, 12.5F, -2F);
      harvest4.setTextureSize(128, 128);
      harvest4.mirror = true;
      setRotation(harvest4, 0F, 0F, 0F);
      harvest5 = new ModelRenderer(this, 0, 11);
      harvest5.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest5.setRotationPoint(-9F, 12.5F, -0.5F);
      harvest5.setTextureSize(128, 128);
      harvest5.mirror = true;
      setRotation(harvest5, 0F, 0F, 0F);
      harvest6 = new ModelRenderer(this, 0, 11);
      harvest6.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest6.setRotationPoint(-7.5F, 12.5F, 1F);
      harvest6.setTextureSize(128, 128);
      harvest6.mirror = true;
      setRotation(harvest6, 0F, 0F, 0F);
      harvest7 = new ModelRenderer(this, 0, 11);
      harvest7.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest7.setRotationPoint(-6F, 12.5F, -0.5F);
      harvest7.setTextureSize(128, 128);
      harvest7.mirror = true;
      setRotation(harvest7, 0F, 0F, 0F);
      harvest8 = new ModelRenderer(this, 0, 11);
      harvest8.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest8.setRotationPoint(8F, 12.5F, -0.5F);
      harvest8.setTextureSize(128, 128);
      harvest8.mirror = true;
      setRotation(harvest8, 0F, 0F, 0F);
      harvest9 = new ModelRenderer(this, 0, 11);
      harvest9.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest9.setRotationPoint(6.5F, 14F, -0.5F);
      harvest9.setTextureSize(128, 128);
      harvest9.mirror = true;
      setRotation(harvest9, 0F, 0F, 0F);
      harvest10 = new ModelRenderer(this, 0, 14);
      harvest10.addBox(0F, 0F, 0F, 2, 2, 2);
      harvest10.setRotationPoint(6F, 12F, -1F);
      harvest10.setTextureSize(128, 128);
      harvest10.mirror = true;
      setRotation(harvest10, 0F, 0F, 0F);
      harvest11 = new ModelRenderer(this, 0, 11);
      harvest11.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest11.setRotationPoint(6.5F, 12.5F, 1F);
      harvest11.setTextureSize(128, 128);
      harvest11.mirror = true;
      setRotation(harvest11, 0F, 0F, 0F);
      harvest12 = new ModelRenderer(this, 0, 11);
      harvest12.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest12.setRotationPoint(6.5F, 11F, -0.5F);
      harvest12.setTextureSize(128, 128);
      harvest12.mirror = true;
      setRotation(harvest12, 0F, 0F, 0F);
      harvest13 = new ModelRenderer(this, 0, 11);
      harvest13.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest13.setRotationPoint(6.5F, 12.5F, -2F);
      harvest13.setTextureSize(128, 128);
      harvest13.mirror = true;
      setRotation(harvest13, 0F, 0F, 0F);
      harvest14 = new ModelRenderer(this, 0, 11);
      harvest14.addBox(0F, 0F, 0F, 1, 1, 1);
      harvest14.setRotationPoint(5F, 12.5F, -0.5F);
      harvest14.setTextureSize(128, 128);
      harvest14.mirror = true;
      setRotation(harvest14, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    planted1.render(f5);
    planted2.render(f5);
    sprout1.render(f5);
    sprout2.render(f5);
    sprout3.render(f5);
    sprout4.render(f5);
    growing.render(f5);
    grown1.render(f5);
    grown2.render(f5);
    grown3.render(f5);
    grown4.render(f5);
    grown5.render(f5);
    grown6.render(f5);
    grown7.render(f5);
    grown8.render(f5);
    grown9.render(f5);
    harvest1.render(f5);
    harvest2.render(f5);
    harvest3.render(f5);
    harvest4.render(f5);
    harvest5.render(f5);
    harvest6.render(f5);
    harvest7.render(f5);
    harvest8.render(f5);
    harvest9.render(f5);
    harvest10.render(f5);
    harvest11.render(f5);
    harvest12.render(f5);
    harvest13.render(f5);
    harvest14.render(f5);
  }
  
  public void render(float f5)
  {
    planted1.render(f5);
    planted2.render(f5);
    sprout1.render(f5);
    sprout2.render(f5);
    sprout3.render(f5);
    sprout4.render(f5);
    growing.render(f5);
    grown1.render(f5);
    grown2.render(f5);
    grown3.render(f5);
    grown4.render(f5);
    grown5.render(f5);
    grown6.render(f5);
    grown7.render(f5);
    grown8.render(f5);
    grown9.render(f5);
    harvest1.render(f5);
    harvest2.render(f5);
    harvest3.render(f5);
    harvest4.render(f5);
    harvest5.render(f5);
    harvest6.render(f5);
    harvest7.render(f5);
    harvest8.render(f5);
    harvest9.render(f5);
    harvest10.render(f5);
    harvest11.render(f5);
    harvest12.render(f5);
    harvest13.render(f5);
    harvest14.render(f5);
  }
  
  public void render(float f5, int section)
  {
	switch(section)
	{
	case 0:
		planted1.render(f5);
	    planted2.render(f5);
	case 1:
		sprout1.render(f5);
	    sprout2.render(f5);
	    sprout3.render(f5);
	    sprout4.render(f5);
	case 2:
		 growing.render(f5);
	case 3:
		grown1.render(f5);
	    grown2.render(f5);
	    grown3.render(f5);
	    grown4.render(f5);
	    grown5.render(f5);
	    grown6.render(f5);
	    grown7.render(f5);
	    grown8.render(f5);
	    grown9.render(f5);
	case 4:
		harvest1.render(f5);
	    harvest2.render(f5);
	    harvest3.render(f5);
	    harvest4.render(f5);
	    harvest5.render(f5);
	    harvest6.render(f5);
	    harvest7.render(f5);
	    harvest8.render(f5);
	    harvest9.render(f5);
	    harvest10.render(f5);
	    harvest11.render(f5);
	    harvest12.render(f5);
	    harvest13.render(f5);
	    harvest14.render(f5);
		break;
	}
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
