// Date: 4/17/2014 6:46:33 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.sudwood.advancedutilities.client.models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelJetpackArmor extends ModelBiped
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
  
  public ModelJetpackArmor(float f)
  {
	  super(f);
    textureWidth = 128;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 3, 9, 3);
      Shape1.setRotationPoint(-4F, 2F, 2F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 3, 9, 3);
      Shape2.setRotationPoint(1F, 2F, 2F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 15, 0);
      Shape3.addBox(0F, 0F, 0F, 2, 2, 1);
      Shape3.setRotationPoint(-1F, 5F, 3F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 25, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape4.setRotationPoint(-5F, 2F, 3F);
      Shape4.setTextureSize(128, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 25, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape5.setRotationPoint(-5F, 10F, 3F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 32);
      Shape6.addBox(0F, 0F, 0F, 1, 12, 1);
      Shape6.setRotationPoint(-6F, -1F, 3F);
      Shape6.setTextureSize(128, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 15);
      Shape7.addBox(0F, 0F, 0F, 1, 12, 1);
      Shape7.setRotationPoint(5F, -1F, 3F);
      Shape7.setTextureSize(128, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 22);
      Shape8.addBox(0F, 0F, 0F, 1, 1, 7);
      Shape8.setRotationPoint(5F, -1F, -4F);
      Shape8.setTextureSize(128, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 22);
      Shape9.addBox(0F, 0F, 0F, 1, 1, 7);
      Shape9.setRotationPoint(-6F, -1F, -4F);
      Shape9.setTextureSize(128, 128);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 34, 0);
      Shape10.addBox(0F, 0F, 0F, 1, 7, 1);
      Shape10.setRotationPoint(5F, 0F, -4F);
      Shape10.setTextureSize(128, 128);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 34, 0);
      Shape11.addBox(0F, 0F, 0F, 1, 7, 1);
      Shape11.setRotationPoint(-6F, 0F, -4F);
      Shape11.setTextureSize(128, 128);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 25, 0);
      Shape12.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape12.setRotationPoint(4F, 2F, 3F);
      Shape12.setTextureSize(128, 128);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 25, 0);
      Shape13.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape13.setRotationPoint(4F, 10F, 3F);
      Shape13.setTextureSize(128, 128);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 42, 0);
      Shape14.addBox(0F, 0F, 0F, 10, 1, 1);
      Shape14.setRotationPoint(-5F, 6F, -4F);
      Shape14.setTextureSize(128, 128);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 42, 0);
      Shape15.addBox(0F, 0F, 0F, 10, 1, 1);
      Shape15.setRotationPoint(-5F, 2F, -4F);
      Shape15.setTextureSize(128, 128);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 44, 7);
      Shape16.addBox(0F, 0F, 0F, 2, 3, 1);
      Shape16.setRotationPoint(-1F, 3F, -4F);
      Shape16.setTextureSize(128, 128);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      
      this.bipedBody.addChild(Shape1);
      this.bipedBody.addChild(Shape2);
      this.bipedBody.addChild(Shape3);
      this.bipedBody.addChild(Shape4);
      this.bipedBody.addChild(Shape5);
      this.bipedBody.addChild(Shape6);
      this.bipedBody.addChild(Shape7);
      this.bipedBody.addChild(Shape8);
      this.bipedBody.addChild(Shape9);
      this.bipedBody.addChild(Shape10);
      this.bipedBody.addChild(Shape11);
      this.bipedBody.addChild(Shape12);
      this.bipedBody.addChild(Shape13);
      this.bipedBody.addChild(Shape14);
      this.bipedBody.addChild(Shape15);
      this.bipedBody.addChild(Shape16);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
