// Date: 4/7/2014 2:02:38 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.sudwood.advancedutilities.client.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSteamSmeltry extends AdvancedModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape30;
    ModelRenderer Shape31;
    ModelRenderer Shape32;
    ModelRenderer Shape33;
    ModelRenderer Shape34;
    ModelRenderer Shape35;
    ModelRenderer Shape36;
    ModelRenderer Shape37;
    ModelRenderer Shape38;
    ModelRenderer Shape39;
    ModelRenderer Shape40;
    ModelRenderer Shape41;
    ModelRenderer Shape42;
    ModelRenderer Shape43;
    ModelRenderer Shape44;
    ModelRenderer Shape45;
    ModelRenderer Shape46;
    ModelRenderer Shape47;
    ModelRenderer Shape48;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
  
  public ModelSteamSmeltry()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
      Shape1.setRotationPoint(-8F, 15F, -8F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape30 = new ModelRenderer(this, 80, 0);
      Shape30.addBox(0F, 0F, 0F, 8, 1, 16);
      Shape30.setRotationPoint(0F, 14F, -8F);
      Shape30.setTextureSize(128, 64);
      Shape30.mirror = true;
      setRotation(Shape30, 0F, 0F, 0F);
      Shape31 = new ModelRenderer(this, 30, 17);
      Shape31.addBox(0F, 0F, 0F, 1, 6, 16);
      Shape31.setRotationPoint(7F, 8F, -8F);
      Shape31.setTextureSize(128, 64);
      Shape31.mirror = true;
      setRotation(Shape31, 0F, 0F, 0F);
      Shape32 = new ModelRenderer(this, 13, 19);
      Shape32.addBox(0F, 0F, 0F, 7, 6, 1);
      Shape32.setRotationPoint(0F, 8F, -8F);
      Shape32.setTextureSize(128, 64);
      Shape32.mirror = true;
      setRotation(Shape32, 0F, 0F, 0F);
      Shape33 = new ModelRenderer(this, 13, 19);
      Shape33.addBox(0F, 0F, 0F, 7, 6, 1);
      Shape33.setRotationPoint(0F, 8F, 7F);
      Shape33.setTextureSize(128, 64);
      Shape33.mirror = true;
      setRotation(Shape33, 0F, 0F, 0F);
      Shape34 = new ModelRenderer(this, 3, 18);
      Shape34.addBox(0F, 0F, 0F, 1, 6, 4);
      Shape34.setRotationPoint(0F, 8F, -7F);
      Shape34.setTextureSize(128, 64);
      Shape34.mirror = true;
      setRotation(Shape34, 0F, 0F, 0F);
      Shape35 = new ModelRenderer(this, 3, 18);
      Shape35.addBox(0F, 0F, 0F, 1, 6, 4);
      Shape35.setRotationPoint(0F, 8F, 3F);
      Shape35.setTextureSize(128, 64);
      Shape35.mirror = true;
      setRotation(Shape35, 0F, 0F, 0F);
      Shape36 = new ModelRenderer(this, 7, 29);
      Shape36.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape36.setRotationPoint(0F, 9F, 2F);
      Shape36.setTextureSize(128, 64);
      Shape36.mirror = true;
      setRotation(Shape36, 0F, 0F, 0F);
      Shape37 = new ModelRenderer(this, 7, 29);
      Shape37.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape37.setRotationPoint(0F, 9F, -3F);
      Shape37.setTextureSize(128, 64);
      Shape37.mirror = true;
      setRotation(Shape37, 0F, 0F, 0F);
      Shape38 = new ModelRenderer(this, 13, 29);
      Shape38.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape38.setRotationPoint(-1F, 11F, -1F);
      Shape38.setTextureSize(128, 64);
      Shape38.mirror = true;
      setRotation(Shape38, 0F, 0F, -0.3346075F);
      Shape39 = new ModelRenderer(this, 13, 29);
      Shape39.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape39.setRotationPoint(-1F, 11F, 0F);
      Shape39.setTextureSize(128, 64);
      Shape39.mirror = true;
      setRotation(Shape39, 0F, 0F, -0.3346075F);
      Shape40 = new ModelRenderer(this, 13, 29);
      Shape40.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape40.setRotationPoint(-1.3F, 10.2F, -1.4F);
      Shape40.setTextureSize(128, 64);
      Shape40.mirror = true;
      setRotation(Shape40, -0.9666506F, 0F, -0.3346075F);
      Shape41 = new ModelRenderer(this, 13, 29);
      Shape41.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape41.setRotationPoint(-1F, 11.1F, 0.8F);
      Shape41.setTextureSize(128, 64);
      Shape41.mirror = true;
      setRotation(Shape41, 0.9666439F, 0F, -0.3346075F);
      Shape42 = new ModelRenderer(this, 19, 32);
      Shape42.addBox(0F, 0F, 0F, 1, 4, 4);
      Shape42.setRotationPoint(0F, 10.7F, -2F);
      Shape42.setTextureSize(128, 64);
      Shape42.mirror = true;
      setRotation(Shape42, 0F, 0F, 0F);
      Shape43 = new ModelRenderer(this, 0, 49);
      Shape43.addBox(0F, 0F, 0F, 6, 1, 14);
      Shape43.setRotationPoint(1F, 8F, -7F);
      Shape43.setTextureSize(128, 64);
      Shape43.mirror = true;
      setRotation(Shape43, 0F, 0F, 0F);
      Shape44 = new ModelRenderer(this, 64, 18);
      Shape44.addBox(0F, 0F, 0F, 5, 1, 10);
      Shape44.setRotationPoint(-7F, 14F, -5F);
      Shape44.setTextureSize(128, 64);
      Shape44.mirror = true;
      setRotation(Shape44, 0F, 0F, 0F);
      Shape45 = new ModelRenderer(this, 97, 18);
      Shape45.addBox(0F, 0F, 0F, 1, 3, 10);
      Shape45.setRotationPoint(-8F, 12F, -5F);
      Shape45.setTextureSize(128, 64);
      Shape45.mirror = true;
      setRotation(Shape45, 0F, 0F, 0F);
      Shape46 = new ModelRenderer(this, 97, 18);
      Shape46.addBox(0F, 0F, 0F, 1, 3, 10);
      Shape46.setRotationPoint(-2F, 12F, -5F);
      Shape46.setTextureSize(128, 64);
      Shape46.mirror = true;
      setRotation(Shape46, 0F, 0F, 0F);
      Shape47 = new ModelRenderer(this, 66, 31);
      Shape47.addBox(0F, 0F, 0F, 7, 3, 1);
      Shape47.setRotationPoint(-8F, 12F, -6F);
      Shape47.setTextureSize(128, 64);
      Shape47.mirror = true;
      setRotation(Shape47, 0F, 0F, 0F);
      Shape48 = new ModelRenderer(this, 66, 31);
      Shape48.addBox(0F, 0F, 0F, 7, 3, 1);
      Shape48.setRotationPoint(-8F, 12F, 5F);
      Shape48.setTextureSize(128, 64);
      Shape48.mirror = true;
      setRotation(Shape48, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape2.setRotationPoint(2F, 23F, -3F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape3.setRotationPoint(-3F, 23F, -3F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape4.setRotationPoint(-3F, 23F, 2F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape5.setRotationPoint(2F, 23F, 2F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 6, 0);
      Shape6.addBox(0F, 0F, 0F, 2, 1, 2);
      Shape6.setRotationPoint(-1F, 23F, -1F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 54, 40);
      Shape7.addBox(0F, 0F, 0F, 10, 3, 10);
      Shape7.setRotationPoint(-5F, 20F, -5F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 102, 52);
      Shape8.addBox(0F, 0F, 0F, 6, 4, 6);
      Shape8.setRotationPoint(-3F, 16F, -3F);
      Shape8.setTextureSize(128, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 0);
      Shape9.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape9.setRotationPoint(5F, 21F, -4F);
      Shape9.setTextureSize(128, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 0);
      Shape10.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape10.setRotationPoint(5F, 21F, 3F);
      Shape10.setTextureSize(128, 64);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 66, 0);
      Shape11.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape11.setRotationPoint(6F, 16F, 3F);
      Shape11.setTextureSize(128, 64);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 66, 0);
      Shape12.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape12.setRotationPoint(6F, 16F, -4F);
      Shape12.setTextureSize(128, 64);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape30.render(f5);
    Shape31.render(f5);
    Shape32.render(f5);
    Shape33.render(f5);
    Shape34.render(f5);
    Shape35.render(f5);
    Shape36.render(f5);
    Shape37.render(f5);
    Shape38.render(f5);
    Shape39.render(f5);
    Shape40.render(f5);
    Shape41.render(f5);
    Shape42.render(f5);
    Shape43.render(f5);
    Shape44.render(f5);
    Shape45.render(f5);
    Shape46.render(f5);
    Shape47.render(f5);
    Shape48.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
  }
  
  public void render(float f5)
  {
	Shape1.render(f5);
    Shape30.render(f5);
    Shape31.render(f5);
    Shape32.render(f5);
    Shape33.render(f5);
    Shape34.render(f5);
    Shape35.render(f5);
    Shape36.render(f5);
    Shape37.render(f5);
    Shape38.render(f5);
    Shape39.render(f5);
    Shape40.render(f5);
    Shape41.render(f5);
    Shape42.render(f5);
    Shape43.render(f5);
    Shape44.render(f5);
    Shape45.render(f5);
    Shape46.render(f5);
    Shape47.render(f5);
    Shape48.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
