// Date: 7/22/2015 8:58:04 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.sudwood.advancedutilities.client.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSteamQuarry extends AdvancedModelBase
{
  //fields
    ModelRenderer base1;
    ModelRenderer base2;
    ModelRenderer base3;
    ModelRenderer base4;
    ModelRenderer base5;
    ModelRenderer base6;
    ModelRenderer basemain;
    ModelRenderer support1;
    ModelRenderer support2;
    ModelRenderer support3;
    ModelRenderer support4;
    ModelRenderer topsupport1;
    ModelRenderer topsupport2;
    ModelRenderer topsupport3;
    ModelRenderer topsupport4;
    ModelRenderer top1;
    ModelRenderer top2;
    ModelRenderer top3;
    ModelRenderer drill1;
    ModelRenderer drill2;
    ModelRenderer drill3;
  
  public ModelSteamQuarry()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      base1 = new ModelRenderer(this, 0, 0);
      base1.addBox(0F, 0F, 0F, 1, 1, 1);
      base1.setRotationPoint(2F, 23F, -3F);
      base1.setTextureSize(128, 128);
      base1.mirror = true;
      setRotation(base1, 0F, 0F, 0F);
      base2 = new ModelRenderer(this, 0, 0);
      base2.addBox(0F, 0F, 0F, 1, 1, 1);
      base2.setRotationPoint(-3F, 23F, -3F);
      base2.setTextureSize(128, 128);
      base2.mirror = true;
      setRotation(base2, 0F, 0F, 0F);
      base3 = new ModelRenderer(this, 0, 0);
      base3.addBox(0F, 0F, 0F, 1, 1, 1);
      base3.setRotationPoint(-3F, 23F, 2F);
      base3.setTextureSize(128, 128);
      base3.mirror = true;
      setRotation(base3, 0F, 0F, 0F);
      base4 = new ModelRenderer(this, 0, 0);
      base4.addBox(0F, 0F, 0F, 1, 1, 1);
      base4.setRotationPoint(2F, 23F, 2F);
      base4.setTextureSize(128, 128);
      base4.mirror = true;
      setRotation(base4, 0F, 0F, 0F);
      base5 = new ModelRenderer(this, 44, 0);
      base5.addBox(0F, 0F, 0F, 2, 1, 2);
      base5.setRotationPoint(-1F, 23F, -1F);
      base5.setTextureSize(128, 128);
      base5.mirror = true;
      setRotation(base5, 0F, 0F, 0F);
      base6 = new ModelRenderer(this, 11, 27);
      base6.addBox(0F, 0F, 0F, 8, 3, 8);
      base6.setRotationPoint(-4F, 20F, -4F);
      base6.setTextureSize(128, 128);
      base6.mirror = true;
      setRotation(base6, 0F, 0F, 0F);
      basemain = new ModelRenderer(this, 69, 0);
      basemain.addBox(0F, 0F, 0F, 13, 1, 14);
      basemain.setRotationPoint(-7F, 19F, -7F);
      basemain.setTextureSize(128, 128);
      basemain.mirror = true;
      setRotation(basemain, 0F, 0F, 0F);
      support1 = new ModelRenderer(this, 2, 29);
      support1.addBox(0F, 0F, 0F, 1, 9, 1);
      support1.setRotationPoint(-7F, 10F, -7F);
      support1.setTextureSize(128, 128);
      support1.mirror = true;
      setRotation(support1, 0F, 0F, 0F);
      support2 = new ModelRenderer(this, 2, 29);
      support2.addBox(0F, 0F, 0F, 1, 9, 1);
      support2.setRotationPoint(5F, 10F, -7F);
      support2.setTextureSize(128, 128);
      support2.mirror = true;
      setRotation(support2, 0F, 0F, 0F);
      support3 = new ModelRenderer(this, 2, 29);
      support3.addBox(0F, 0F, 0F, 1, 9, 1);
      support3.setRotationPoint(-7F, 10F, 6F);
      support3.setTextureSize(128, 128);
      support3.mirror = true;
      setRotation(support3, 0F, 0F, 0F);
      support4 = new ModelRenderer(this, 2, 29);
      support4.addBox(0F, 0F, 0F, 1, 9, 1);
      support4.setRotationPoint(5F, 10F, 6F);
      support4.setTextureSize(128, 128);
      support4.mirror = true;
      setRotation(support4, 0F, 0F, 0F);
      topsupport1 = new ModelRenderer(this, 0, 40);
      topsupport1.addBox(0F, 0F, 0F, 11, 1, 1);
      topsupport1.setRotationPoint(-6F, 10F, -7F);
      topsupport1.setTextureSize(128, 128);
      topsupport1.mirror = true;
      setRotation(topsupport1, 0F, 0F, 0F);
      topsupport2 = new ModelRenderer(this, 0, 40);
      topsupport2.addBox(0F, 0F, 0F, 11, 1, 1);
      topsupport2.setRotationPoint(-6F, 10F, 6F);
      topsupport2.setTextureSize(128, 128);
      topsupport2.mirror = true;
      setRotation(topsupport2, 0F, 0F, 0F);
      topsupport3 = new ModelRenderer(this, 0, 45);
      topsupport3.addBox(0F, 0F, 0F, 1, 1, 12);
      topsupport3.setRotationPoint(-7F, 10F, -6F);
      topsupport3.setTextureSize(128, 128);
      topsupport3.mirror = true;
      setRotation(topsupport3, 0F, 0F, 0F);
      topsupport4 = new ModelRenderer(this, 0, 45);
      topsupport4.addBox(0F, 0F, 0F, 1, 1, 12);
      topsupport4.setRotationPoint(5F, 10F, -6F);
      topsupport4.setTextureSize(128, 128);
      topsupport4.mirror = true;
      setRotation(topsupport4, 0F, 0F, 0F);
      top1 = new ModelRenderer(this, 0, 6);
      top1.addBox(0F, 0F, 0F, 3, 1, 12);
      top1.setRotationPoint(-2F, 10F, -6F);
      top1.setTextureSize(128, 128);
      top1.mirror = true;
      setRotation(top1, 0F, 0F, 0F);
      top2 = new ModelRenderer(this, 0, 62);
      top2.addBox(0F, 0F, 0F, 4, 1, 4);
      top2.setRotationPoint(1F, 10F, -2F);
      top2.setTextureSize(128, 128);
      top2.mirror = true;
      setRotation(top2, 0F, 0F, 0F);
      top3 = new ModelRenderer(this, 0, 62);
      top3.addBox(0F, 0F, 0F, 4, 1, 4);
      top3.setRotationPoint(-6F, 10F, -2F);
      top3.setTextureSize(128, 128);
      top3.mirror = true;
      setRotation(top3, 0F, 0F, 0F);
      drill1 = new ModelRenderer(this, 33, 7);
      drill1.addBox(0F, 0F, 0F, 5, 3, 6);
      drill1.setRotationPoint(-3F, 11F, -3F);
      drill1.setTextureSize(128, 128);
      drill1.mirror = true;
      setRotation(drill1, 0F, 0F, 0F);
      drill2 = new ModelRenderer(this, 0, 72);
      drill2.addBox(0F, 0F, 0F, 3, 2, 4);
      drill2.setRotationPoint(-2F, 14F, -2F);
      drill2.setTextureSize(128, 128);
      drill2.mirror = true;
      setRotation(drill2, 0F, 0F, 0F);
      drill3 = new ModelRenderer(this, 47, 27);
      drill3.addBox(0F, 0F, 0F, 1, 1, 2);
      drill3.setRotationPoint(-1F, 16F, -1F);
      drill3.setTextureSize(128, 128);
      drill3.mirror = true;
      setRotation(drill3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    base1.render(f5);
    base2.render(f5);
    base3.render(f5);
    base4.render(f5);
    base5.render(f5);
    base6.render(f5);
    basemain.render(f5);
    support1.render(f5);
    support2.render(f5);
    support3.render(f5);
    support4.render(f5);
    topsupport1.render(f5);
    topsupport2.render(f5);
    topsupport3.render(f5);
    topsupport4.render(f5);
    top1.render(f5);
    top2.render(f5);
    top3.render(f5);
    drill1.render(f5);
    drill2.render(f5);
    drill3.render(f5);
  }
  
  public void render(float f5)
  {
    base1.render(f5);
    base2.render(f5);
    base3.render(f5);
    base4.render(f5);
    base5.render(f5);
    base6.render(f5);
    basemain.render(f5);
    support1.render(f5);
    support2.render(f5);
    support3.render(f5);
    support4.render(f5);
    topsupport1.render(f5);
    topsupport2.render(f5);
    topsupport3.render(f5);
    topsupport4.render(f5);
    top1.render(f5);
    top2.render(f5);
    top3.render(f5);
    drill1.render(f5);
    drill2.render(f5);
    drill3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
